[package]
name = "cert-surfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
ctclient = "0.4.5"
openssl = "0.10.61"
reqwest = { version = "0.11.22", features = ["blocking"] }
